macro(export_submodule Libraries)
    foreach (lib ${Libraries})
        list(APPEND Sub_Library "${lib}")
    endforeach ()
    set(Sub_Library ${Sub_Library} PARENT_SCOPE)
endmacro()

macro(export_include includes)
    foreach (include ${includes})
        list(APPEND Sub_Include "${include}")
    endforeach ()
    set(Sub_Include ${Sub_Include} PARENT_SCOPE)
endmacro()

function(show_details SUB_MODULE_NAME Dependencies Libraries)
    message(STATUS "----------------------------------------------------------------")
    message(STATUS "Submodule ${SUB_MODULE_NAME} Contains")
    message(STATUS "Depends on Include:")
    foreach (_dep ${Dependencies})
        message(STATUS "${_dep}: ${${_dep}_INCLUDE_DIRS}")
    endforeach ()

    message(STATUS "Depends on Library")
    foreach (_dep ${Dependencies})
        message(STATUS "${_dep}: ${${_dep}_LIBRARIES}")
    endforeach ()

    message(STATUS "Compile Library: ${Libraries}")
    message(STATUS "----------------------------------------------------------------")
endfunction()